# Generated by Django 5.2.1 on 2025-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznici',
            fields=[
                ('id_sap', models.IntegerField(default=1111111111, primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
                ('ulice', models.CharField(max_length=100)),
                ('poznamka', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
