# Generated by Django 5.2.1 on 2025-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaznici',
            name='poznamka',
            field=models.TextField(max_length=100),
        ),
    ]
