# Generated by Django 5.2.1 on 2025-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaznici', '0002_alter_zakaznici_poznamka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaznici',
            name='poznamka',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
